### ISSUE TITLE
Feature: テーブルコンポーネント

### ISSUE THREAD

**Issue by book000** [jaoafa/jao-ui#29]
なにかしらのデータを表示する場合に、テーブルを扱うケースがあるのでテーブルコンポーネントが欲しいです。(少なくとも直近では https://github.com/jaoafa/jaoweb/issues/32)
横スクロール・ページネーション・ソーティングあたりがあると嬉しいです。

参考までに Vuetify の `v-data-table` を…
https://vuetifyjs.com/en/components/data-tables/

他の issue を全て追えてないので、被っていたら非常に申し訳ない。

**Comment by Hiratake** [comment]
`j-table` をつくりました。
