### ISSUE TITLE
Git-Flowのreleaseブランチのマージを自動化する

### ISSUE THREAD

**Issue by Hiratake** [jaoafa/jao-ui#42]
Git-Flow では release ブランチを main と dev にマージする必要があるので自動化する。([参考](https://www.atlassian.com/ja/git/tutorials/comparing-workflows/gitflow-workflow))

**Comment by Hiratake** [comment]
なんもわからんので保留

- `main` と `dev` はブランチのプロテクトがかかってるのでそれぞれPRなげるようにする
  - `release/v*.*.*` ブランチが作成されたら `npm version v*.*.*` を実行して `package.json` のバージョンを上げてコミット
  - `main` と `dev` にPRなげる
- `main` にPRがマージされたら、
  - `main` のマージコミットにバージョンのタグをつける
  -  `npm pack` と `npm publish` を実行して GitHub Packages に最新版をなげる
  - マージされたPRの履歴からリリースノート自動生成してRelease追加、もしくはCHANGELOG.mdを作成して中身を追記とかできたらなおよし

**Comment by Hiratake** [comment]
GitHub Actions で hub コマンド使えるっぽいからゴリ押せばワンチャンありそう  
https://github.com/github/hub#github-actions

**Comment by book000** [comment]
> `release/v*.*.*` ブランチが作成されたら

https://github.community/t/trigger-job-on-branch-created/16878/5

1. Get version text: `release/v*.*.*` -> `v*.*.*`
2. Run `npm version v*.*.*` on shell
3. コミット
4. プルリク作成 https://github.com/marketplace/actions/create-pull-request

> `main` にPRがマージされたら

https://qiita.com/okazy/items/7ab46f2c20ec341a2836

1. タグ作成 https://scrapbox.io/ohbarye/GitHub_Actions%E3%81%A7git_tag%E3%82%92%E8%87%AA%E5%8B%95%E7%94%9F%E6%88%90
2. Run `npm pack`, `npm publish` on shell
3. チェンジログの作成・取得 https://github.com/marketplace/actions/generate-changelog-action

**Comment by Hiratake** [comment]
それはそう

**Comment by Hiratake** [comment]
> 3. コミット
> 4. プルリク作成 https://github.com/marketplace/actions/create-pull-request

ひるくらいにプルリクつくるやつ試してたけど、コミットしてから動かすと差分がないとかでPRなげてくれないから `hub` コマンドでむりやりやろうかな～とか考えてた。

**Comment by book000** [comment]
ふむ

**Comment by Hiratake** [comment]
マージしたあとのやつ作ってないのに閉じちゃった

**Comment by Hiratake** [comment]
https://github.com/marketplace/actions/release-changelog-builder

**Comment by Hiratake** [comment]
よくわからんのでなし
